/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface WcFurigana {}
}

declare global {


  interface HTMLWcFuriganaElement extends Components.WcFurigana, HTMLStencilElement {}
  var HTMLWcFuriganaElement: {
    prototype: HTMLWcFuriganaElement;
    new (): HTMLWcFuriganaElement;
  };
  interface HTMLElementTagNameMap {
    'wc-furigana': HTMLWcFuriganaElement;
  }
}

declare namespace LocalJSX {
  interface WcFurigana {}

  interface IntrinsicElements {
    'wc-furigana': WcFurigana;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'wc-furigana': LocalJSX.WcFurigana & JSXBase.HTMLAttributes<HTMLWcFuriganaElement>;
    }
  }
}


