/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface HFurigana {
    /**
    * Japanese to display
    */
    'value': string;
  }
}

declare global {


  interface HTMLHFuriganaElement extends Components.HFurigana, HTMLStencilElement {}
  var HTMLHFuriganaElement: {
    prototype: HTMLHFuriganaElement;
    new (): HTMLHFuriganaElement;
  };
  interface HTMLElementTagNameMap {
    'h-furigana': HTMLHFuriganaElement;
  }
}

declare namespace LocalJSX {
  interface HFurigana {
    /**
    * Japanese to display
    */
    'value'?: string;
  }

  interface IntrinsicElements {
    'h-furigana': HFurigana;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'h-furigana': LocalJSX.HFurigana & JSXBase.HTMLAttributes<HTMLHFuriganaElement>;
    }
  }
}


